
export const modules = {
    features: true,
    gallery: true,
    maps: true,
    contact: true,
    skills: true,
    countto: true,
    team: true,
    faq: true,
    login: true,
    slider: true,
    pricing: true,
    forms: true,
    countdown: true,
    timeline: true,
    filters: true,
    quotes: true,
    feedback: true,
    video: true,
    autotype: false,
    multinav: true,
    multilang: true,
    consent: true,
    blog: false,
    search: false,
    analytics: false,
    logo: false,
    textsupply: false
}
